<?xml version="1.0"?>
<package format="3">
  <name>voxblox</name>
  <version>0.0.0</version>
  <description>Voxfield: non-projective signed distance field for online planning and 3D reconstruction</description>

  <maintainer email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</maintainer>
  <maintainer email="marius.fehr@mavt.ethz.ch">Marius Fehr</maintainer>
  <maintainer email="yuepan@student.ethz.ch">Yue Pan</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>eigen3</build_depend>
  <exec_depend>eigen3</exec_depend>

  <build_depend>gflags</build_depend>
  <exec_depend>gflags</exec_depend>

  <build_depend>glog</build_depend>
  <exec_depend>glog</exec_depend>

  <build_depend>minkindr</build_depend>
  <exec_depend>minkindr</exec_depend>

  <build_depend>protobuf</build_depend>
  <exec_depend>protobuf</exec_depend>

  <build_depend>voxblox_msgs</build_depend>

</package>
