<?xml version="1.0"?>
<package format="3">
  <name>voxblox_ros</name>
  <version>0.0.0</version>
  <description>Voxblox ROS2 interface (migration target for Humble).</description>

  <maintainer email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</maintainer>
  <maintainer email="marius.fehr@mavt.ethz.ch">Marius Fehr</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rclcpp</build_depend>
  <exec_depend>rclcpp</exec_depend>

  <build_depend>std_msgs</build_depend>
  <exec_depend>std_msgs</exec_depend>

  <build_depend>sensor_msgs</build_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <build_depend>nav_msgs</build_depend>
  <exec_depend>nav_msgs</exec_depend>

  <build_depend>geometry_msgs</build_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <build_depend>cv_bridge</build_depend>
  <exec_depend>cv_bridge</exec_depend>

  <build_depend>tf2_ros</build_depend>
  <exec_depend>tf2_ros</exec_depend>

  <build_depend>tf2_eigen</build_depend>
  <exec_depend>tf2_eigen</exec_depend>

  <build_depend>pcl_conversions</build_depend>
  <exec_depend>pcl_conversions</exec_depend>

  <build_depend>voxblox</build_depend>
  <exec_depend>voxblox</exec_depend>

  <build_depend>voxblox_msgs</build_depend>
  <exec_depend>voxblox_msgs</exec_depend>

  <build_depend>voxblox_rviz_plugin</build_depend>
  <exec_depend>voxblox_rviz_plugin</exec_depend>

  <depend>tf2_geometry_msgs</depend>

  <build_depend>minkindr</build_depend>
  <exec_depend>minkindr</exec_depend>

  <build_depend>minkindr_conversions</build_depend>
  <exec_depend>minkindr_conversions</exec_depend>

  <depend>interactive_markers</depend>
</package>
